<h1>Fins/Xapian FullText Server</h1>
<b>Index: <%$index.name%></b>

<table>
<tr>
<th>
Number of Documents
</th>
<th>
Highest Document ID
</th>
<th>
Average Document Length
</th>
<th>
Has Positional Info?
</th>
<tr>
<td>
  <%$index.doccount%>
</td>
<td>
  <%$index.maxdoc%>
</td>
<td>
  <%$index.avlength%>
</td>
<td>
  <%boolean var="$index.positions"%>
</td>
</tr>
<table>
<!--
<p>
<%action_form action="info" args="$index.name"%>
Term Count: <input type="term" length="40"> <input type="submit">
<%if data->term %> 
<p>
<b><%$index.termcount%></b> documents match the term <b>"<%$index.term%>"..
<%endif%>
</form>
-->
